name: fixed-income-analytics
version: '0.0.0.1'
category: Finance
author: Juri Chomé
maintainer: example@example.com
copyright: 2018 Juri Chomé
license: BSD3
homepage: https://github.com/2mol/fixed-income-analytics
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
- base >= 4.7 && < 5
- time
- containers
- pretty-simple
- ieee754
- cassava
- bytestring
- vector
- yaml

executables:
  fixed-income-analytics:
    main: Main.hs
    source-dirs: src

tests:
  doctest:
    main: DocTest
    source-dirs:
    - test
    dependencies:
    - doctest
    - Glob
